### ISSUE TITLE
WrapProcessPipeline

### ISSUE THREAD

**Issue by ledor473** [smacker/opentracing-go-redis#2]
Currently, this library only uses [`WrapProcess`](https://godoc.org/github.com/go-redis/redis#Client.WrapProcess) to instrument `go-redis`, but there's also [`WrapProcessPipeline`](https://godoc.org/github.com/go-redis/redis#Client.WrapProcessPipeline) that could be used.

Would you be open to receive a PR with this feature enhancement ?

**Comment by smacker** [comment]
sure! Thank you.
