### ISSUE TITLE
Span duration not captured

### ISSUE THREAD

**Issue by thebinary** [smacker/opentracing-go-redis#4]
Though the trace captures the command and details. the duration of span is not captured in the trace.

**Comment by smacker** [comment]
Thank you for bug report! I see you have already fixed the issue. Do you mind to create a PR with it?

**Comment by thebinary** [comment]
i have opened the PR #5. The travis CI fails, because the newer go-redis client (v7) deprecated WrapProcess/WrapProcessPipeline in favor of newer AddHook. But this version may still be required by many like me. So, for keeping this still compatible with older go-redis, and success in CI, may be we can lock the go-redis version to 6.15.x. and include it in the CI.

**Comment by smacker** [comment]
fixed by #5
